### ISSUE TITLE
Improve CarPlay german text for `sync_appearance_message`

### ISSUE THREAD

**Issue by DerAndereAndi** [iternio/abrp-translations#189]
The current takes causes the selection to show up with scrollbars. Maybe the text can be improved and made shorter, so that there is more space for the selection without the need for the scrollbars.

This would be my suggestion:

```
Setze auf welcher Seite die Daten angezeigt werden.
```

This translates to `Set the side on which the data should appear`. The current sentence is quite hard to understand as it is also very technical. Why not ask the user instead: 

```
Is this car left or right side driving?
```

which would turn the answer texts around, but is easier to understand. Or something similar.

![image-1](https://user-images.githubusercontent.com/42185/161761788-87cfdf70-c391-4042-bb4d-6ca39d8d77b4.png)

What do you think?

**Comment by iternio** [comment]
I think that proposal works well. 

Ideally, at some point, we will entirely remove this option and just detect it from CarPlay, but since CarPlay is even worse documented than other Apple APIs, we simply have not yet found a way.

**Comment by TomTomZoe** [comment]
@DerAndereAndi 
Please take a look at the latest improvement. The description is now shorter and easier to understand.

**Comment by TomTomZoe** [comment]
@DerAndereAndi
I think this issue can be closed now. :-)
