### ISSUE TITLE
Misspelled identifiers in en.json?

### ISSUE THREAD

**Issue by TomTomZoe** [iternio/abrp-translations#200]
There are two identifiers that may have a misspelling that I'm not sure the software pulls up correctly as I've never read the relevant sentences in the application before:

**remeber**_to_replan
https://github.com/iternio/abrp-translations/blob/58a5551232dc20d15fc580fdded83549a05baddb/en.json#L1123

need_ccs_**outisde**_of_na_error
https://github.com/iternio/abrp-translations/blob/58a5551232dc20d15fc580fdded83549a05baddb/en.json#L1130

@iternio Are these two errors and the translations are currently not being used by the application, or are there the same spelling mistakes in the application's source code, which is why you shouldn't change anything in the translation now?

**Comment by iternio** [comment]
Thanks for spotting it! We will have to change it in the application and will make sure to do the same change in the translation files.

**Comment by TomTomZoe** [comment]
Issue is fixed:
https://github.com/iternio/abrp-translations/blob/f918bb6fa758833c8ef2587306cffc9661005493/en.json#L1098
https://github.com/iternio/abrp-translations/blob/f918bb6fa758833c8ef2587306cffc9661005493/en.json#L1135
Thank you very much @iternio
