### ISSUE TITLE
da.json

### ISSUE THREAD

**Issue by swesterhoff** [iternio/abrp-translations#247]
"headwind": "modvind",
"tailwind": "medvind",

It's not showing in the app, showing "head" or "tail" in options for the wind.

**Comment by iternio** [comment]
Right! I have added it on our backlog to be fixed soon.

**Comment by TomTomZoe** [comment]
Same as [here](https://github.com/iternio/abrp-translations/issues/26) two years ago :-)

**Comment by iternio** [comment]
Better late than never, issue has now been fixed in our code and will be part of next release :)
