### ISSUE TITLE
German translation of "How would you like to treat {{network}} chargers?" shows no effect

### ISSUE THREAD

**Issue by TomTomZoe** [iternio/abrp-translations#25]
There seems to be a language dependent text for the question "How would you like to treat ... chargers?" of the dialog "Prefer or avoid: ...". A translation is available in both the English and German language files:
en.json: "how_to_treat": "How would you like to treat {{network}} chargers?",
de.json: "how_to_treat": "Wie möchtest Du {{network}} Ladepunkte behandeln?",

Obviously the language-specific sentence is not used, at least not in the German version of ABRP.
It would be nice to fix this.

![Prefer or avoid Charger](https://user-images.githubusercontent.com/66869770/84870973-46e5f700-b080-11ea-8071-ea3d3fd90f37.JPG)

**Comment by rowich** [comment]
what about "Umgang mit {{network}}" for the title and "" (nothing) for
"how_to_treat"?

Not translated items are due to ongoing development and extension of the
application. Whenever I have time or see that something is not
translated I am doing the same as you do right now: Check and try to
find out how it could fit. And it requires most of the time two or three
approaches to have it fit into different screen types. The very first
german version was a nightmare and I was very happy to get a
preproduction version from Bo before going into production.

Am 17/06/2020 um 10:07 schrieb TomTomZoe:

**Comment by TomTomZoe** [comment]
Good idea. "Umgang mit {{network}}" is heading in the right direction :-), sounds better than the actual translation.

The same words are also used in the following dialogue:

![Charger Information](https://user-images.githubusercontent.com/66869770/84892239-7eaf6780-b09d-11ea-87f4-d3ce4c8e86fd.JPG)

At the end of the day, it's all about assigning priorities from 1 (preferably exclusive) to 4 (whatever) for route planning.
So what about "Priorität von {{network}}" for title in the first dialogue and at the star in the second?

Probably the very first German version was an automatic translation?
I have also had the experience with "one two tries until the texts fit in" :-)

**Comment by rowich** [comment]
sounds good.

No, the very first translation was done from me, but without really
knowning the context of the text and how it would fit into the available
space. I even needed to find a common naming first like "Ladepunkt" and
the usual "Du/Sie". Took some tries to get it working.

And yes, same for you additional example.

Am 17/06/2020 um 13:39 schrieb TomTomZoe:

**Comment by TomTomZoe** [comment]
Great work, @rowich.
Then I will commit '"Priority of "{{network}}' along with other changes that are currently in progress.

@iternio 
The reason for the non-functioning
en.json: "how_to_treat": "How would you like to treat {{network}} chargers?",
de.json: "how_to_treat": ....
remains to be clarified  ;-)

**Comment by TomTomZoe** [comment]
The language-specific sentence is now used in the german version of ABRP.
Thank you.
