### ISSUE TITLE
Missing translation at charging processes on the route

### ISSUE THREAD

**Issue by TomTomZoe** [iternio/abrp-translations#27]
I did not find a translation for the "FOR", "TO" and "at" at charging processes on the route, neither in en.json nor de.json.

It would be nice if this little texts were also language specific :-)

![For](https://user-images.githubusercontent.com/66869770/84885945-04c6b080-b094-11ea-9fbe-8c77d2bcf962.JPG)
![To](https://user-images.githubusercontent.com/66869770/84885950-06907400-b094-11ea-91a3-5318e28095d9.JPG)

**Comment by rowich** [comment]
both not new. Already reported to Bo, no change so far ;-)

Am 17/06/2020 um 12:18 schrieb TomTomZoe:

**Comment by PomkHU** [comment]
Same for the hungarian translation.
I suppose these are functional buttons which are not part of the language file.

**Comment by SamuelBrucksch** [comment]
German translation should be there now @TomTomZoe

**Comment by TomTomZoe** [comment]
Thank you @SamuelBrucksch
